export enum httpStatus {
    OK = 200,
    CREATED = 201,
    ACCEPTED = 202,
    NO_CONTENT = 204,

    BAD_REQUEST = 400,
    UNAUTHORIZED = 401,
    PAYMENT_REQUIRED = 402,
    FORBIDDEN = 403,
    NOT_FOUND = 404,
    REQUEST_TIMEOUT = 408,
    CONFLICT = 409,
    PAYLOAD_TOO_LARGE = 413,
    UNPROCESSABLE_ENTITY = 422,
    TOO_MANY_REQUESTS = 429,

    INTERNAL_SERVER_ERROR = 500,
    BAD_GATEWAY = 502,
    SERVICE_UNAVAILABLE = 503,
}

export const MESSAGE = {
    ALREADY_EXIST: "Already Exists!",
    AUTHORIZATION_TOKEN_MISSING: "Authorization Token is Missing or Invalid!",
    AUTHENTICATION_SUCCESS: "Authentication Successful!",
    FETCHED_SUCCESSFULLY: "Fetched Successfully.",
    CREATED_SUCCESSFULLY: "Created Successfully.",
    ADDED_SUCCESSFULLY: "Added Successfully.",
    UPDATED_SUCCESSFULLY: "Updated Successfully.",
    REGISTERED_SUCCESSFULLY: "Registered Successfully.",
    REGISTRATION_FAILED: "Registration Failed!",
    CREATION_FAILED: "Creation Failed!",
    UPDATION_FAILED: "Update Failed!",
    SOMETHING_WENT_WRONG: "Something Went Wrong!",
    UNEXPECTED_ERROR: "Unexpected Error Occurred!",
    INVALID_OR_EXPIRED_TOKEN: "Invalid or Expired Token!",
    PAYLOAD_MISSING_OR_INVALID: "User Payload is Missing or Invalid!",
    MISSING_OR_INVALID: "is Missing or Invalid!",
    THIS_NOT_FOUND: "Not Found or Inactive!",
    USER_NOT_FOUND: "User Not Found or Inactive!",
    ROLE_NOT_RECOGNIZED: "Role Not Recognized!",
    MISSING_REQUIRED_FIELD: "Missing Required Fields",
    NO_CONTENT: "No Content",
    DATA_NOT_FOUND: "Data Not Found",
    ACCOUNT_ALREADY_EXISTS: "Account with this email already exists",
    INVALID_CREDENTIALS: "Invalid credentials",
    LOGGED_OUT_SUCCESSFULLY: "Logged out successfully",
};